joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

gripper_controller:
  type: effort_controllers/JointGroupEffortController
  joints: 
    - gripper_body-finger1
    - gripper_body-finger2