gripper_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

gripper_controller:
  type: effort_controllers/JointGroupPositionController
  joints: 
    - finger1_joint
    - finger2_joint

  finger1_joint: 
    pid: {p: 0.1, i: 0.0, d: 1.0}
  finger2_joint: 
    pid: {p: 0.1, i: 0.0, d: 1.0}
  